### ISSUE TITLE
Fail to preview a story

### ISSUE THREAD

**Issue by mericda** [irllabs/simplevr#63]
I'm trying to create a story with this pano

https://commons.wikimedia.org/wiki/File:Harderwijk_harbour_2018_-_360_panorama.jpg

I see the edit preview, but 3d preview doesn't work and shows this screen: 

![image](https://user-images.githubusercontent.com/19254822/111916049-69a1a380-8a36-11eb-8dec-df4ff2f54481.png)

Not sure what is the error here, is it because the asset is too large, is it loading? @lazarmitic

**Comment by mericda** [comment]
When I go back to the edit view, it shows like this: 

![image](https://user-images.githubusercontent.com/19254822/111916108-9e155f80-8a36-11eb-92f3-698d608da502.png)

**Comment by lazarmitic** [comment]
Checking, it would be helpful if you can provide screenshot of browser console as well when you run into a problem, it would help a lot with pinpointing the issue :)

**Comment by lazarmitic** [comment]
When creating a story, application takes input photo and resizes it to proper dimensions, during that process image size changes, in my case, final image size on Firebase Storage is 6.2mb (which is not a lot, original size is 9mb).

Can you send me a link to that story if you have it saved, so that I can check image size on your end. (should be same as in my case).

In the meantime I will add some kind of dialog that shows loading progress.

**Comment by lazarmitic** [comment]
Also, can you tell me Browser/OS that you are using.

**Comment by lazarmitic** [comment]
I think I found the issue, resolving.

**Comment by lazarmitic** [comment]
Fixed issue, when preloading image for preview it was being converted to .png that takes way too much space (50mb), that's why all of the loading/navigation was too slow.
